name = "CementChemistry"
uuid = "f346e401-14f9-407c-a0e2-c4f64a3e574a"
authors = ["Jean-François Barthélémy and Anthony Soive"]
version = "0.1.0-dev"

[deps]
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
PeriodicTable = "1.2.1"
PhysicalConstants = "0.2.4"
Unicode = "1.11.0"
Unitful = "1.24.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
